### PR TITLE
Small addings on service + vehicules routes

### PR DESCRIPTION
**Pull request by t4ms**
Adding on contrator routes

### CODE REVIEW

**Comment by Jennie-QIAN** [comment]
`router.put('/services/:id', (req, res, next) => {
    Contractor.findByIdAndUpdate(req.user._id,
        { $pull:{ services: req.body.deletedService } },
        )
    .then( () => {
        res.json({ message: `Service with ${req.params.id} is removed successfully.` });
    })
    .catch( err => {
        res.status(500).json(err);
    });
});`

**Comment by Jennie-QIAN** [comment]
```
router.put('/services/:id', (req, res, next) => {
    Contractor.findByIdAndUpdate(req.user._id,
        { $pull:{ services: req.body.deletedService } },
        )
    .then( () => {
        res.json({ message: `Service with ${req.params.id} is removed successfully.` });
    })
    .catch( err => {
        res.status(500).json(err);
    });
});
```

**Comment by Jennie-QIAN** [comment]
Besides this change, there are lots of differences in the contractor.js due to my merges,
if u can do git pull on main,
then git checkout servicesVehiculesAdding, then git rebase main, to handle the conflicts, that would be great :)
I changed a lot on populate and response and stuff...

**Comment by t4ms** [comment]
I have created a new branch "servicesVehiculesAdding2".

**Pull request closed without merging**
